server:
  port: 8081
  address: 0.0.0.0


#Redis配置
##Redis数据库索引（默认为0）
spring:
#  thymeleaf:
#    mode: HTML
#    prefix: classpath:static/
#    cache: false
#    suffix: .html
  #数据库配置信息
  datasource:
    username: root
    password: WENbo9533
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
          max-active: 1024
          max-wait: 10000
          max-idle: 200
          min-idle: 0


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springbootredis.entity

#配置log
#logging:
#  config: loglearn\src\main\resources\log4j2.xml
#  level:
#    com:
#      example:
#        springbootredis:
#          dao: debug
#    root: trace